" Tab Configuration
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Call the .vimrc.plug file
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

set termguicolors
