export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="fino"
plugins=(git zsh-syntax-highlighting command-not-found)
ZSH_COLORIZE_STYLE="colorful"
source $ZSH/oh-my-zsh.sh

# Alias
# apt install grc bat exa tmux vim 
alias nmap="sudo grc nmap"
alias cat="batcat --style=plain"
alias ping="grc ping"
alias ifconfig="grc ifconfig"

alias ls="exa -lhg --color=always"
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
